# Generated by Django 3.2.3 on 2021-06-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_comment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='import_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
